### ISSUE TITLE
Failed to launch in A100 nvcc fatal   : Unsupported gpu architecture 'compute_80'

### ISSUE THREAD

**Issue by momo1986** [NVlabs/DiffPure#15]
Thanks for sharing, it is a wonderful job.

I run it in Nvidia A100 machine.
![image](https://user-images.githubusercontent.com/34225874/215036011-f47e788b-b961-44c7-b0da-fc5be662fdad.png)
CUDA is 11.4.

However, it has a problem to load library package.
```
Traceback (most recent call last):
  File "/anaconda/envs/RobustART/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1723, in _run_ninja_build
    env=env)
  File "/anaconda/envs/RobustART/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "eval_sde_adv.py", line 29, in <module>
    from runners.diffpure_sde import RevGuidedDiffusion
  File "/home/v-junyan1/adv_training/DiffPure/runners/diffpure_sde.py", line 17, in <module>
    from score_sde.losses import get_optimizer
  File "/home/v-junyan1/adv_training/DiffPure/score_sde/losses.py", line 22, in <module>
    from .models import utils as mutils
  File "/home/v-junyan1/adv_training/DiffPure/score_sde/models/__init__.py", line 15, in <module>
    from . import  ncsnpp
  File "/home/v-junyan1/adv_training/DiffPure/score_sde/models/ncsnpp.py", line 18, in <module>
    from . import utils, layers, layerspp, normalization
  File "/home/v-junyan1/adv_training/DiffPure/score_sde/models/layerspp.py", line 20, in <module>
    from . import up_or_down_sampling
  File "/home/v-junyan1/adv_training/DiffPure/score_sde/models/up_or_down_sampling.py", line 18, in <module>
    from ..op import upfirdn2d
  File "/home/v-junyan1/adv_training/DiffPure/score_sde/op/__init__.py", line 9, in <module>
    from .fused_act import FusedLeakyReLU, fused_leaky_relu
  File "/home/v-junyan1/adv_training/DiffPure/score_sde/op/fused_act.py", line 23, in <module>
    os.path.join(module_path, "fused_bias_act_kernel.cu"),
  File "/anaconda/envs/RobustART/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1136, in load
    keep_intermediates=keep_intermediates)
  File "/anaconda/envs/RobustART/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1347, in _jit_compile
    is_standalone=is_standalone)
  File "/anaconda/envs/RobustART/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1452, in _write_ninja_file_and_build_library
    error_prefix=f"Error building extension '{name}'")
  File "/anaconda/envs/RobustART/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1733, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'fused': [1/2] /usr/bin/nvcc  -DTORCH_EXTENSION_NAME=fused -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /anaconda/envs/RobustART/lib/python3.6/site-packages/torch/include -isystem /anaconda/envs/RobustART/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -isystem /anaconda/envs/RobustART/lib/python3.6/site-packages/torch/include/TH -isystem /anaconda/envs/RobustART/lib/python3.6/site-packages/torch/include/THC -isystem /anaconda/envs/RobustART/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_80,code=compute_80 -gencode=arch=compute_80,code=sm_80 --compiler-options '-fPIC' -std=c++14 -c /home/v-junyan1/adv_training/DiffPure/score_sde/op/fused_bias_act_kernel.cu -o fused_bias_act_kernel.cuda.o
FAILED: fused_bias_act_kernel.cuda.o
/usr/bin/nvcc  -DTORCH_EXTENSION_NAME=fused -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /anaconda/envs/RobustART/lib/python3.6/site-packages/torch/include -isystem /anaconda/envs/RobustART/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -isystem /anaconda/envs/RobustART/lib/python3.6/site-packages/torch/include/TH -isystem /anaconda/envs/RobustART/lib/python3.6/site-packages/torch/include/THC -isystem /anaconda/envs/RobustART/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_80,code=compute_80 -gencode=arch=compute_80,code=sm_80 --compiler-options '-fPIC' -std=c++14 -c /home/v-junyan1/adv_training/DiffPure/score_sde/op/fused_bias_act_kernel.cu -o fused_bias_act_kernel.cuda.o
nvcc fatal   : Unsupported gpu architecture 'compute_80'
ninja: build stopped: subcommand failed.
```

This error happens when running eval_sde_adv.py.

How could I resolve the problem of nvcc fatal   : Unsupported gpu architecture 'compute_80'

Should I change the hardware system to run the code or should I implement other workarounds?

I wish you are all good. 

Thanks & Regards!
Momo

**Comment by weilinie** [comment]
Can you use cuda 11.0 instead? I would recommend to follow the docker environment to run the code.
