### ISSUE TITLE
Error when loading pretrained CIFAR10 checkpoint

### ISSUE THREAD

**Issue by keenlooks** [NVlabs/DiffPure#2]
Hello,

I get the below error when trying to execute this command from the README. I have downloaded the pre-trained models and put in a pretrained dir, renamed them to what the code expects (from `checkpoint_8` to `checkpoint_8.pth` and put them in a `score_sde` directory)

It looks to me that this file is being loaded with `torch.load` in this repo [here](https://github.com/NVlabs/DiffPure/blob/master/runners/diffpure_sde.py#L43) but in the original code it is loaded with `tf.io.gfile.GFile` at https://github.com/yang-song/score_sde/blob/main/utils.py#L46

Is there some pre-processing I should be doing with this pre-trained model file? Thanks for your help! Error below...

```
root@c5460383ad15:/workspace/run_scripts/cifar10# bash run_cifar_rand_inf.sh 1 1  
INFO - eval_sde_adv.py - 2022-06-17 12:43:49,903 - Using device: cuda
ngpus: 1, adv_batch_size: 64
starting the model and loader...
using cifar10 wideresnet-28-10...
diffusion_type: sde
model_config: Namespace(data=Namespace(category='cifar10', centered=True, dataset='CIFAR10', image_size=32, num_channels=3, random_flip=True, uniform_dequantization=False), device=device(type='cuda'), model=Namespace(attention_type='ddpm', attn_resolutions=[16], beta_max=20.0, beta_min=0.1, ch_mult=[1, 2, 2, 2], conditional=True, conv_size=3, dropout=0.1, ema_rate=0.9999, embedding_type='positional', fir=False, fir_kernel=[1, 3, 3, 1], fourier_scale=16, init_scale=0.0, name='ncsnpp', nf=128, nonlinearity='swish', normalization='GroupNorm', num_res_blocks=8, num_scales=1000, progressive='none', progressive_combine='sum', progressive_input='none', resamp_with_conv=True, resblock_type='biggan', scale_by_sigma=False, sigma_max=50, sigma_min=0.01, skip_rescale=True), optim=Namespace(beta1=0.9, eps=1e-08, grad_clip=1.0, lr=0.0002, optimizer='Adam', warmup=5000, weight_decay=0), sampling=Namespace(corrector='none', method='pc', n_steps_each=1, noise_removal=True, predictor='euler_maruyama', probability_flow=False, snr=0.16), training=Namespace(continuous=True, n_iters=950001, reduce_mean=True, sde='vpsde'))
Traceback (most recent call last):
  File "eval_sde_adv.py", line 322, in <module>
    robustness_eval(args, config)
  File "eval_sde_adv.py", line 224, in robustness_eval
    model = SDE_Adv_Model(args, config)
  File "eval_sde_adv.py", line 47, in __init__
    self.runner = RevGuidedDiffusion(args, config, device=config.device)
  File "/workspace/runners/diffpure_sde.py", line 181, in __init__
    restore_checkpoint(f'{model_dir}/checkpoint_8.pth', state, device)
  File "/workspace/runners/diffpure_sde.py", line 43, in restore_checkpoint
    loaded_state = torch.load(ckpt_dir, map_location=device)
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 595, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 764, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: unpickling stack underflow
```

**Comment by keenlooks** [comment]
I was able to fix this by using the models from the [pytorch implementation of score_sde](https://github.com/yang-song/score_sde_pytorch) instead of the one linked in the README.

**Comment by weilinie** [comment]
Hi @keenlooks, great to hear you figure it out. I just updated the readme to explicitly provide the download link to models.
